#!/usr/bin/env bash

set -e

########### Variables ###########
get_config=""
proton_drive_email=""
config_exists=false
current_dir=$(pwd)
timestamp=$(date +%s)
disable_install_apps=false
drive_folder=""

########### Applications ###########
brew_apps=(
  git
  zsh
  zsh-completions
  zsh-syntax-highlighting
  zsh-autosuggestions
  go
  awscli
  aws-iam-authenticator
  terraform
  helm
  kubectx
  argocd
  stow
  tflint
  terraform-docs
  golangci-lint
  eza
)

brew_cask_apps_base=(
  ghostty
  arc
  spotify
  visual-studio-code
  slack
  alt-tab
  proton-drive
  discord
  vlc
  bambu-studio
  parsec
)

########### Kubectl Plugins ###########
kubectl_plugins=(

)

########### Dock ###########
dock_apps=(
  "Visual Studio Code"
  "Spotify"
  "Slack"
  "Arc"
)

dock_system_apps=(
  "Finder"
  "System Preferences"
  "Dock"
)

########### Functions ###########
function install_macos_apps() {
  # Install xcode command line tools
  echo "🕑 Installing xcode command line tools."
  if command -v xcode-select -p >/dev/null; then
    echo "⏩ Xcode command line tools seems to already be installed; skipping."
  else
    xcode-select --install
    echo "✅ Xcode command line tools installed."
  fi

  # Install homebrew
  echo "🕑 Installing brew."
  if command -v /opt/homebrew/bin/brew >/dev/null; then
    echo "⏩ Brew seems to already be installed; skipping."
  else
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    echo "✅ Brew installed."
  fi

  # install rosetta
  echo "🕑 Installing rosetta."
  if $(/usr/sbin/softwareupdate --install-rosetta --agree-to-license >/dev/null 2>&1); then
    echo "✅ Rosetta installed."
  else
    echo "❌ Rosetta failed to install."
  fi

  # install brew apps
  echo "🕑 Installing brew apps."
  brew_apps_install
  echo "✅ Brew apps installed."

  # install brew cask apps
  echo "🕑 Installing brew cask apps."
  brew_cask_apps_install
  echo "✅ Brew cask apps installed."
}

# install brew apps if not installed
function brew_apps_install() {
  for app in "${brew_apps[@]}"; do
    if ! $(/opt/homebrew/bin/brew list $app >/dev/null 2>&1); then
      echo "🕑 Installing $app."
      /opt/homebrew/bin/brew install $app >/dev/null 2>&1 && echo "✅ $app installed." || echo "❌ $app failed to install."
    else 
      echo "⏩ $app seems to already be installed; skipping."
    fi
  done
}

# install brew cask apps if not installed
function brew_cask_apps_install() {
  brew_cask_apps=("${brew_cask_apps_base[@]}")
  for app in "${brew_cask_apps[@]}"; do
    mac_name=$(app_rename $app)
    if ! $(/opt/homebrew/bin/brew list $app >/dev/null 2>&1) && [[ -z $(ls /Applications | tr '[:upper:]' '[:lower:]' | grep "$mac_name") ]]; then
      echo "🕑 Installing $app."
      /opt/homebrew/bin/brew install --cask $app >/dev/null 2>&1 && echo "✅ $app installed." || echo "❌ $app failed to install."
    else 
      echo "⏩ $app seems to already be installed; skipping."
    fi
  done
}

function upgrade_apps() {
  echo "🕑 Upgrading brew apps."
  if $(/opt/homebrew/bin/brew upgrade >/dev/null 2>&1); then
    echo "✅ Brew apps Upgraded."
  else
    echo "❌ Brew apps failed to upgrade."
  fi
}

## Check if Proton Drive is ready
function proton_drive_is_ready() {
  if [[ -z $proton_drive_email ]]; then
    echo "no email"
  fi
  if [[ -z $(ls ~/Library/CloudStorage | grep "$drive_folder") ]]; then
    echo "no proton drive folder"
  else
    drive_folder=$(ls ~/Library/CloudStorage | grep "ProtonDrive")
    echo "proton drive ready"
  fi
}

function stow_folders() {
  cd ~/.dotfiles
  echo "🕑 Stowing folders."
  /opt/homebrew/bin/stow -R -t ~ git
  cd zsh
  /opt/homebrew/bin/stow -R -t ~ config
  cd ..
  /opt/homebrew/bin/stow -R -t ~ tfswitch
  echo "✅ Folders stowed."
}

function app_rename() {
  case $1 in
    alt-tab)
      echo "alttab"
      ;;
    visual-studio-code)
      echo "visual studio code"
      ;;
    bambu-studio)
      echo "bambustudio"
      ;;
    proton-drive)
      echo "proton drive"
      ;;
    *)
      echo $1
      ;;
  esac
}

function get_private_config() {
  echo "🕑 Checking if Proton Drive is ready for getting private config."
  status=$(proton_drive_is_ready)
  if [[ "$status" != "proton drive ready" ]]; then
    echo "❌ Proton Drive not ready; $status; skipping."
    return
  fi
  echo "🕑 Getting private config."
  mkdir -p ~/{.aws,.kube}
  cd ~/Library/CloudStorage/$drive_folder/dotfiles/personal
  /opt/homebrew/bin/stow -t ~/.kube kube
  /opt/homebrew/bin/stow -t ~/.kube aws
  cd ~
  echo "✅ Private config retrieved."
}



function macos_config_command() {
  # Disable .DS_Store files on network volumes
  defaults write com.apple.desktopservices DSDontWriteNetworkStores true
  # Remove finder tags
  defaults write com.apple.finder ShowRecentTags -bool false
  # Change scroll direction to natural
  defaults write -g com.apple.swipescrolldirection -bool false
  # Dock icon size
  defaults write com.apple.dock tilesize -int 32
  # Disable last used app in dock
  defaults write com.apple.dock show-recents -bool false  
  # Application in dock
  for app in "${dock_apps[@]}"; do
    defaults write com.apple.dock persistent-apps -array-add '<dict><key>tile-data</key><dict><key>file-data</key><dict><key>_CFURLString</key><string>/Applications/'$app'.app</string><key>_CFURLStringType</key><integer>0</integer></dict></dict></dict>'
  done
  # System apps in dock
  for app in "${dock_system_apps[@]}"; do
    defaults write com.apple.dock persistent-others -array-add '<dict><key>tile-data</key><dict><key>file-data</key><dict><key>_CFURLString</key><string>/System/Applications/'$app'.app</string><key>_CFURLStringType</key><integer>0</integer></dict></dict></dict>'
  done

  # Kill dock
  killall Dock
}

## Configure kubectl
function kubectl_configure() {
  echo "🕑 Configuring kubectl."
  echo "🕑 Install Krew."
  cd "$(mktemp -d)" &&
    OS="$(uname | tr '[:upper:]' '[:lower:]')" &&
    ARCH="$(uname -m | sed -e 's/x86_64/amd64/' -e 's/\(arm\)\(64\)\?.*/\1\2/' -e 's/aarch64$/arm64/')" &&
    KREW="krew-${OS}_${ARCH}" &&
    curl -fsSLO "https://github.com/kubernetes-sigs/krew/releases/latest/download/${KREW}.tar.gz" &&
    tar zxvf "${KREW}.tar.gz" &&
    ./"${KREW}" install krew >/dev/null 2>&1 && echo "✅ Krew installed." || echo "❌ Krew failed to install."
  
  cd $current_dir
  echo "🕑 Installing kubectl plugins."
  for plugin in "${kubectl_plugins[@]}"; do
    if ! $(/opt/homebrew/bin/kubectl krew list | grep "$plugin" >/dev/null 2>&1); then
      echo "🕑 Installing $plugin."
      /opt/homebrew/bin/kubectl krew install "$plugin" >/dev/null 2>&1 && echo "✅ $plugin installed." || echo "❌ $plugin failed to install."
    else 
      echo "⏩ $plugin seems to already be installed; skipping."
    fi
  done
}

## Get git repos
function get_git_repo() {
  echo "🕑 Getting git repos."
  echo "🕑 Checking if Proton Drive is ready for getting repo list."
  status=$(proton_drive_is_ready)
  if [[ "$status" != "proton drive ready" ]]; then
    echo "❌ Proton Drive not ready; $status; skipping."
    return
  fi
  echo "🕑 Getting git repo for personal computer."
  mkdir -p ~/{personal,biz}
  clone_repos personal
}

## Clone repos from repo list in Proton Drive
function clone_repos() {
  folder=$1
  cd ~/$folder
  if [[ -z $(test ~/Library/CloudStorage/$drive_folder/dotfiles/personal/git-repos) ]]; then
    echo "❌ No git repos list found; skipping."
    return
  else
    for repo in $(cat ~/Library/CloudStorage/$drive_folder/dotfiles/personal/git-repos); do
      git clone "$repo"
    done
  fi
  cd ..
}

## Configure ssh config
function stow_ssh_config() {
  echo "🕑 Configuring ssh config."
  echo "🕑 Checking if Proton Drive is ready for getting ssh config."
  status=$(proton_drive_is_ready)
  if [[ "$status" != "proton drive ready" ]]; then
    echo "❌ Proton Drive not ready; $status; skipping."
    return
  fi

  echo "🕑 Getting ssh config."
  if [ -d ~/.ssh ]; then
    mv ~/.ssh ~/.ssh-old-$timestamp
  fi
  mkdir -p ~/.ssh
  cd ~/Library/CloudStorage/$drive_folder/dotfiles/personal
  /opt/homebrew/bin/stow -R -t ~/.ssh ssh
  cd ~
  echo "✅ Ssh config retrieved."
}

## Configure terraform
function terraform_config() {
  echo "🕑 Configuring terraform."
  cd ~/.dotfiles
  /opt/homebrew/bin/stow -R -t ~/ terraform
  echo "✅ Terraform config retrieved."
}

function install_fonts() {
  "🕑 Installing fonts."
  cd ~/.dotfiles/fonts
  cp * ~/Library/Fonts
  echo "✅ Fonts installed."
}

## Get script config
function get_script_config() {
  if [[ -f .config ]]; then
    get_config=$(cat .config | grep get_config | cut -d "=" -f2)
    proton_drive_email=$(cat .config | grep proton_drive_email | cut -d "=" -f2)
    config_exists=true
  fi

  if [[ "$config_exists" == "false" ]]; then
    echo "❓ Get private config from Proton Drive? (y/n)"
    read -r get_config

    if [ "$get_config" == "y" ]; then
      echo "❓ Enter Proton Drive email:"
      read -r proton_drive_email
    fi

    echo "get_config=$get_config" >>.config
    echo "proton_drive_email=$proton_drive_email" >>.config
  fi
}

## Configure computer based on config
function configure_computer() {
  if [[ "$disable_install_apps" == "false" ]]; then
    install_macos_apps
  fi
  proton_drive_is_ready
  stow_ssh_config
  terraform_config
  stow_folders
  get_private_config
  kubectl_configure
  macos_config_command
  # get_git_repo
}

########### Main ###########
case $1 in
  upgrade| -u | --upgrade)
    echo "🕑 Upgrading all apps."
    upgrade_apps
    echo "✅ All apps upgraded."
    exit 0
    ;;
  configure_computer | -c | --configure_computer)
    if [[ $2 == "--no-install-app" ]] || [[ $2 == "-nia" ]]; then
      disable_install_apps=true
    fi
    echo "🕑 Configuring computer."
    get_script_config
    configure_computer
    exit 0
    ;;
  debug | -d | --debug)
    echo "🕑 Debugging."
    get_script_config
    echo "get_config=$get_config"
    echo "proton_drive_email=$proton_drive_email"
    echo "proton_drive_status=$(proton_drive_is_ready)"
    echo "current_dir=$current_dir"
    echo "✅ Debugging complete."
    exit 0
    ;;
  * | -h | --help)
    echo "⏩ Valid options are:"
    echo "     Upgrade all apps >> upgrade | -u | --upgrade"
    echo "     Configure computer >> configure_computer | -c | --configure_computer"
    echo "        Configure computer without installing apps >> configure_computer -c --no-install-app | -nia"
    echo "     Debug >> debug | -d | --debug"
    echo "     Help >> * | -h | --help"
    exit 0
    ;;
esac

