#!/usr/bin/env bash

set -e

########### Variables ###########
computer_type=""
get_config=""
proton_drive_email=""
config_exists=false
current_dir=$(pwd)

########### Applications ###########
brew_apps=(
  git
  zsh
  zsh-completions
  zsh-syntax-highlighting
  zsh-autosuggestions
  go
  bruno
  awscli
  aws-iam-authenticator
  m1ddc
  terraform
  helm
  kubectl
  kubectx
  argocd
  stow
  warrensbox/tap/tfswitch
  tflint
  terraform-docs
)

brew_cask_apps_base=(
  iterm2
  arc
  spotify
  visual-studio-code
  notion
  slack
  alt-tab
  raycast
  tableplus
  amethyst
  proton-drive
  elgato-stream-deck
)

brew_cask_apps_personal=(
  discord
  twitch
  vlc
  bambu-studio
  parsec
)

brew_cask_apps_work=(
  zoom
  openvpn-connect
  aws-vpn-client
)

########### Kubectl Plugins ###########
kubectl_plugins=(
  switch-config
  socks5-proxy
)

########### Functions ###########
function install_macos_apps() {
  # Install xcode command line tools
  echo "🕑 Installing xcode command line tools."
  if command -v xcode-select -p >/dev/null; then
    echo "⏩ Xcode command line tools seems to already be installed; skipping."
  else
    xcode-select --install
    echo "✅ Xcode command line tools installed."
  fi

  # Install homebrew
  echo "🕑 Installing brew."
  if command -v /opt/homebrew/bin/brew >/dev/null; then
    echo "⏩ Brew seems to already be installed; skipping."
  else
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    echo "✅ Brew installed."
  fi

  # install rosetta
  echo "🕑 Installing rosetta."
  if $(/usr/sbin/softwareupdate --install-rosetta --agree-to-license >/dev/null 2>&1); then
    echo "✅ Rosetta installed."
  else
    echo "❌ Rosetta failed to install."
  fi

  # install brew apps
  echo "🕑 Installing brew apps."
  brew_apps_install
  echo "✅ Brew apps installed."

  # install brew cask apps
  echo "🕑 Installing brew cask apps."
  brew_cask_apps_install
  echo "✅ Brew cask apps installed."
}

# install brew apps if not installed
function brew_apps_install() {
  for app in "${brew_apps[@]}"; do
    if ! $(/opt/homebrew/bin/brew list $app >/dev/null 2>&1); then
      echo "🕑 Installing $app."
      /opt/homebrew/bin/brew install $app >/dev/null 2>&1 && echo "✅ $app installed." || echo "❌ $app failed to install."
    else 
      echo "⏩ $app seems to already be installed; skipping."
    fi
  done
}

# install brew cask apps if not installed
function brew_cask_apps_install() {
  if [ "$computer_type" == "w" ]; then
    brew_cask_apps=("${brew_cask_apps_base[@]}" "${brew_cask_apps_work[@]}")
  else
    brew_cask_apps=("${brew_cask_apps_base[@]}" "${brew_cask_apps_personal[@]}")
  fi
  for app in "${brew_cask_apps[@]}"; do
    mac_name=$(app_rename $app)
    if ! $(/opt/homebrew/bin/brew list $app >/dev/null 2>&1) && [[ -z $(ls /Applications | tr '[:upper:]' '[:lower:]' | grep "$mac_name") ]]; then
      echo "🕑 Installing $app."
      /opt/homebrew/bin/brew install --cask $app >/dev/null 2>&1 && echo "✅ $app installed." || echo "❌ $app failed to install."
    else 
      echo "⏩ $app seems to already be installed; skipping."
    fi
  done
}

function upgrade_apps() {
  echo "🕑 Upgrading brew apps."
  if $(/opt/homebrew/bin/brew upgrade >/dev/null 2>&1); then
    echo "✅ Brew apps Upgraded."
  else
    echo "❌ Brew apps failed to upgrade."
  fi
}

## Check if Proton Drive is ready
function proton_drive_is_ready() {
  if [[ -z $proton_drive_email ]]; then
    echo "no email"
  fi
  if [[ -z $(ls ~/Library/CloudStorage | grep "ProtonDrive-$proton_drive_email") ]]; then
    echo "no proton drive folder"
  else
    echo "proton drive ready"
  fi
}

function stow_folders() {
  cd ~/.dotfiles
  echo "🕑 Stowing folders."
  /opt/homebrew/bin/stow -R -t ~ git
  cd zsh
  /opt/homebrew/bin/stow -R -t ~ config
  cd ..
  /opt/homebrew/bin/stow -R -t ~ tfswitch
  echo "✅ Folders stowed."
}

function app_rename() {
  case $1 in
    iterm2)
      echo "iterm"
      ;;
    alt-tab)
      echo "alttab"
      ;;
    visual-studio-code)
      echo "visual studio code"
      ;;
    aws-vpn-client)
      echo "aws vpn client"
      ;;
    bambu-studio)
      echo "bambustudio"
      ;;
    proton-drive)
      echo "proton drive"
      ;;
    *)
      echo $1
      ;;
  esac
}

function get_private_config() {
  echo "🕑 Checking if Proton Drive is ready for getting private config."
  status=$(proton_drive_is_ready)
  if [[ "$status" != "proton drive ready" ]]; then
    echo "❌ Proton Drive not ready; $status; skipping."
    return
  fi
  echo "🕑 Getting private config."
  if [[ computer_type -eq "w" ]]; then
    echo "🕑 Getting private config for work computer."
    mkdir -p ~/{.aws,.kube}
    cd ~/Library/CloudStorage/ProtonDrive-$proton_drive_email/dotfiles/work
    /opt/homebrew/bin/stow -t ~/.aws aws
    /opt/homebrew/bin/stow -t ~/.kube kube
    cd ~
    echo "✅ Private config for work computer retrieved."
  else
    echo "🕑 Getting private config for personal computer."
    mkdir ~/{.kube}
    cd ~/Library/CloudStorage/ProtonDrive-$proton_drive_email/dotfiles/personal
    /opt/homebrew/bin/stow -t ~/.kube kube
    cd ~
    echo "✅ Private config for personal computer retrieved."
  fi
}

function macos_config_command() {
  defaults write com.apple.desktopservices DSDontWriteNetworkStores true # Disable .DS_Store files on network volumes
}

## Configure kubectl
function kubectl_configure() {
  echo "🕑 Configuring kubectl."
  echo "🕑 Install Krew."
  cd "$(mktemp -d)" &&
    OS="$(uname | tr '[:upper:]' '[:lower:]')" &&
    ARCH="$(uname -m | sed -e 's/x86_64/amd64/' -e 's/\(arm\)\(64\)\?.*/\1\2/' -e 's/aarch64$/arm64/')" &&
    KREW="krew-${OS}_${ARCH}" &&
    curl -fsSLO "https://github.com/kubernetes-sigs/krew/releases/latest/download/${KREW}.tar.gz" &&
    tar zxvf "${KREW}.tar.gz" &&
    ./"${KREW}" install krew >/dev/null 2>&1 && echo "✅ Krew installed." || echo "❌ Krew failed to install."
  
  cd $current_dir
  echo "🕑 Installing kubectl plugins."
  for plugin in "${kubectl_plugins[@]}"; do
    if ! $(/opt/homebrew/bin/kubectl krew list | grep "$plugin" >/dev/null 2>&1); then
      echo "🕑 Installing $plugin."
      /opt/homebrew/bin/kubectl krew install "$plugin" >/dev/null 2>&1 && echo "✅ $plugin installed." || echo "❌ $plugin failed to install."
    else 
      echo "⏩ $plugin seems to already be installed; skipping."
    fi
  done
}

## Get git repos
function get_git_repo() {
  echo "🕑 Getting git repos."
  echo "🕑 Checking if Proton Drive is ready for getting repo list."
  status=$(proton_drive_is_ready)
  if [[ "$status" != "proton drive ready" ]]; then
    echo "❌ Proton Drive not ready; $status; skipping."
    return
  fi
  if [[ $computer_type -eq "w" ]]; then
    echo "🕑 Getting git repo for work computer."
    mkdir -p ~/work
    clone_repos work
  else
    echo "🕑 Getting git repo for personal computer."
    mkdir -p ~/{personal,biz}
    clone_repos personal
    clone_repos biz
  fi
}

## Clone repos from repo list in Proton Drive
function clone_repos() {
  folder=$1
  cd ~/$folder
  if [[ -z $(test ~/Library/CloudStorage/ProtonDrive-$proton_drive_email/dotfiles/personal/git-repos) ]]; then
    echo "❌ No git repos list found; skipping."
    return
  else
    for repo in $(cat ~/Library/CloudStorage/ProtonDrive-$proton_drive_email/dotfiles/personal/git-repos); do
      git clone "$repo"
    done
  fi
  cd ..
}

## Configure ssh config
function stow_ssh_config() {
  echo "🕑 Configuring ssh config."
  echo "🕑 Checking if Proton Drive is ready for getting ssh config."
  status=$(proton_drive_is_ready)
  if [[ "$status" != "proton drive ready" ]]; then
    echo "❌ Proton Drive not ready; $status; skipping."
    return
  fi

  echo "🕑 Getting ssh config."
  if [ -d ~/.ssh ]; then
    mv ~/.ssh ~/.ssh-old
  fi
  mkdir -p ~/.ssh
  cd ~/Library/CloudStorage/ProtonDrive-$proton_drive_email/dotfiles/personal
  /opt/homebrew/bin/stow -R -t ~/.ssh ssh
  cd ~
  echo "✅ Ssh config retrieved."
}

function install_fonts() {
  "🕑 Installing fonts."
  cd ~/.dotfiles/fonts
  cp * ~/Library/Fonts
  echo "✅ Fonts installed."
}

## Get script config
function get_script_config() {
  if [[ -f .config ]]; then
    computer_type=$(cat .config | grep computer_type | cut -d "=" -f2)
    get_config=$(cat .config | grep get_config | cut -d "=" -f2)
    proton_drive_email=$(cat .config | grep proton_drive_email | cut -d "=" -f2)
    config_exists=true
  fi

  if [[ "$config_exists" == "false" ]]; then
    # Ask if the computer is for work or personal
    echo "❓ Is this computer for work or personal? (w/p)"
    read -r computer_type

    echo "❓ Get private config from Proton Drive? (y/n)"
    read -r get_config

    if [ "$get_config" == "y" ]; then
      echo "❓ Enter Proton Drive email:"
      read -r proton_drive_email
    fi

    echo "computer_type=$computer_type" >>.config
    echo "get_config=$get_config" >>.config
    echo "proton_drive_email=$proton_drive_email" >>.config
  fi
}

## Configure computer based on config
function configure_computer() {
  install_macos_apps
  stow_ssh_config
  stow_folders
  get_private_config
  kubectl_configure
  get_git_repo
}

########### Main ###########
case $1 in
  upgrade| -u | --upgrade)
    echo "🕑 Upgrading all apps."
    upgrade_apps
    echo "✅ All apps upgraded."
    exit 0
    ;;
  configure_computer | -c | --configure_computer)
    echo "🕑 Configuring computer."
    get_script_config
    configure_computer
    exit 0
    ;;
  debug | -d | --debug)
    echo "🕑 Debugging."
    get_script_config
    echo "computer_type=$computer_type"
    echo "get_config=$get_config"
    echo "proton_drive_email=$proton_drive_email"
    echo "proton_drive_status=$(proton_drive_is_ready)"
    echo "current_dir=$current_dir"
    echo "✅ Debugging complete."
    exit 0
    ;;
  * | -h | --help)
    echo "⏩ Valid options are:"
    echo "     Upgrade all apps >> upgrade | -u | --upgrade"
    echo "     Configure computer >> configure_computer | -c | --configure_computer"
    echo "     Debug >> debug | -d | --debug"
    echo "     Help >> * | -h | --help"
    exit 0
    ;;
esac
