#!/bin/bash

# Install xcode command line tools
xcode-select --install

# Install homebrew
if [ ! -d "/opt/homebrew" ]; then
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

# install rosetta
sudo softwareupdate --install-rosetta

# Install brew packages
/opt/homebrew/bin/brew install git
/opt/homebrew/bin/brew install zsh
/opt/homebrew/bin/brew install zsh-completions
/opt/homebrew/bin/brew install zsh-syntax-highlighting
/opt/homebrew/bin/brew install zsh-autosuggestions
/opt/homebrew/bin/brew install go
/opt/homebrew/bin/brew install bruno
/opt/homebrew/bin/brew install m1ddc

# Install brew cask packages
/opt/homebrew/bin/brew install --cask iterm2
/opt/homebrew/bin/brew install --cask arc
/opt/homebrew/bin/brew install --cask spotify
/opt/homebrew/bin/brew install --cask visual-studio-code
/opt/homebrew/bin/brew install --cask notion
/opt/homebrew/bin/brew install --cask slack
/opt/homebrew/bin/brew install --cask alt-tab
/opt/homebrew/bin/brew install --cask bambu-studio
/opt/homebrew/bin/brew install --cask raycast

# Configure desktop/term
# configure zsh
stow zsh
