#!/usr/bin/env bash

set -e

# Ask if the computer is for work or personal
echo "❓ Is this computer for work or personal? (w/p)"
read -r computer_type

brew_apps=(
  git
  zsh
  zsh-completions
  zsh-syntax-highlighting
  zsh-autosuggestions
  go
  bruno
  awscli
  aws-iam-authenticator
  m1ddc
  terraform
  helm
  kubectl
  kubectx
  argocd
)

brew_cask_apps_base=(
  iterm2
  arc
  spotify
  visual-studio-code
  notion
  slack
  alt-tab
  raycast
)

brew_cask_apps_personal=(
  discord
  twitch
  vlc
  bambu-studio
)

brew_cask_apps_work=(
  zoom
)

stow_folders=(
  zsh/config
  git
)

########### Functions ###########
function install_macos_apps() {
  # Install xcode command line tools
  echo "🕑 Installing xcode command line tools."
  if command -v xcode-select -p >/dev/null; then
    echo "⏩ Xcode command line tools seems to already be installed; skipping."
  else
    xcode-select --install
    echo "✅ Xcode command line tools installed."
  fi

  # Install homebrew
  echo "🕑 Installing brew."
  if command -v /opt/homebrew/bin/brew >/dev/null; then
    echo "⏩ Brew seems to already be installed; skipping."
  else
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    echo "✅ Brew installed."
  fi


  # install rosetta
  echo "🕑 Installing rosetta."
  /usr/sbin/softwareupdate --install-rosetta --agree-to-license >/dev/null 2>&1 && echo "✅ Rosetta installed." || echo "❌ Rosetta failed to install."; exit 1

  # install brew apps
  echo "🕑 Installing brew apps."
  brew_apps_install
  echo "✅ Brew apps installed."

  # install brew cask apps
  echo "🕑 Installing brew cask apps."
  brew_cask_apps_install
  echo "✅ Brew cask apps installed."
}

# install brew apps if not installed
function brew_apps_install() {
  for app in "${brew_apps[@]}"; do
    if ! $(/opt/homebrew/bin/brew list $app >/dev/null 2>&1); then
      echo "🕑 Installing $app."
      /opt/homebrew/bin/brew install $app >/dev/null 2>&1 && echo "✅ $app installed." || echo "❌ $app failed to install."
    else 
      echo "⏩ $app seems to already be installed; skipping."
    fi
  done
}

# install brew cask apps if not installed
function brew_cask_apps_install() {
  if [ "$computer_type" == "w" ]; then
    brew_cask_apps=("${brew_cask_apps_base[@]}" "${brew_cask_apps_work[@]}")
  else
    brew_cask_apps=("${brew_cask_apps_base[@]}" "${brew_cask_apps_personal[@]}")
  fi
  for app in "${brew_cask_apps[@]}"; do
    if ! $(/opt/homebrew/bin/brew list $app >/dev/null 2>&1); then
      echo "🕑 Installing $app."
      /opt/homebrew/bin/brew install --cask $app >/dev/null 2>&1 && echo "✅ $app installed." || echo "❌ $app failed to install."
    else 
      echo "⏩ $app seems to already be installed; skipping."
    fi
  done
}

function stow_folders() {
  for folder in "${stow_folders[@]}"; do
    echo "🕑 Stowing $folder."
    stow $folder
    echo "✅ $folder stowed."
  done
}

########### Main ###########
# if macos
if [ "$(uname)" == "Darwin" ]; then
  install_macos_apps
fi

# stow folders
stow_folders
